### ISSUE TITLE
bug hunting

### ISSUE THREAD

**Issue by Adamtaranto** [kdmurray91/mpg#1]
Only works if I comment out all print statements the contain 'file=stderr' in main.py
and change seq input are from unicode to str on line 76 of counter.py
i.e. kmers = iter_kmers(str(subseq), self.k)

**Comment by kdm9** [comment]
Are you using python2 or python3? It requires python3

**Comment by Adamtaranto** [comment]
Python 2

**Comment by kdm9** [comment]
Should now work with python2
